### ISSUE TITLE
Package URL in PackageReference hover tooltip can be incorrect if the version is not a simple version

### ISSUE THREAD

**Issue by Tyrrrz** [tintoy/msbuild-project-tools-server#15]
Hi there.

Given `<PackageReference Include="AngleSharp" Version="[0.9.11]" />`, when I click on "NuGet Package: AngleSharp" link, I get error 404 because it includes square brackets in the URL.

Offending code here:

https://github.com/tintoy/msbuild-project-tools-server/blob/da8e2c07803c2a53be91f2987c1a4e23ce52ab17/src/LanguageServer.Engine/ContentProviders/HoverContentProvider.cs#L177-L180

**Comment by tintoy** [comment]
Hi - thanks, that's a nice catch!

I think in this scenario (version is a range), it might be simplest to link to the latest version of the package (i.e. `/{packageId}` rather than `/{packageId}/{packageVersion}`. It's possible to look up the latest package version that satisfies the version range, but the NuGet API tends to be quite slow and I suspect that users would find this more annoying than not linking to a specific version.

How does that sound to you?

**Comment by Tyrrrz** [comment]
I think `[0.9.11]` should link to 0.9.11 becuase putting square brackets means you're locking the dependency to a specific version, so it makes sense this way. :)

For `0.9.*` of course it would be amazing if it linked to the last 0.9.x version but I understand the effort is just not worth it, so linking to the last package version is good enough.

For `(0.9.11)` or `(0.9.11]` or `(0.9.11,0.11]` or any other combination it would also be great if it managed to find the last version in range, but last package version is also satisfiable.

If you need, here's the list of all possible version notations in `PackageReference`: https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards

**Comment by tintoy** [comment]
Thanks - let's see what we can do, then! 😉

**Comment by tintoy** [comment]
I might be able to cheat by pulling the version out of `project.assets.json`.

Advantages:
* Quick
* Always links to the version you're _actually_ using.

Disadvantages:
* Only works if packages have been restored.  
  If they haven't been restored yet (or haven't been restored since the project's list of `PackageReference`s was modified) then the package Id won't be a hyperlink, just a label (perhaps with some hint text saying "package not restored yet").



 but this will only work if packages have already been restored.

**Comment by Tyrrrz** [comment]
That solution sounds great :)

**Comment by tintoy** [comment]
Hi - sorry, I haven't forgotten about this but work has been a little crazy. Hoping to tackle this on Thursday or on the weekend at the latest :)

**Comment by Tyrrrz** [comment]
No worries, this is definitely not a showstopper by any means :)
